cdn:
  serve-route: /assets
  upload-route: /upload
  address: 0.0.0.0:9743
  advanced:
    read-timeout: 0s
    read-header-timeout: 3s
    write-timeout: 0s
    idle-timeout: 60s

serve:
  asset-dir: ./data/assets
  max-cacheable-size: 100MiB
  cache-size: 1GiB
  asset-ttl: 60s
  advanced:
    write-buffer-size: 4096
    write-window: 10s

upload:
  temp-dir: ./data/tmp
  output-dir: ./data/assets
  url-prefix: /assets
  max-upload-size: 2GiB

auth:
  # Set the issuer's 32-byte Ed25519 public key, encoded as standard padded base64.
  public-key: ""

token-store:
  dbdriver: sqlite
  dbpath: ./data/ts.sql
  advanced:
    db-op-timeout: 3s
    db-cleanup-interval: 60s

metrics:
  address: 127.0.0.1:9884
  endpoint: /metrics
  advanced:
    shutdown-timeout: 3s
